# https://book.getfoundry.sh/reference/config/overview

[profile.default]
remappings = [
	'@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/',
]

# forge i foundry-rs/forge-std
# forge i ensdomains/ens-contracts
# forge i OpenZeppelin/openzeppelin-contracts
